# Generated by Django 2.0.1 on 2018-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action_flag',
            field=models.NullBooleanField(),
        ),
    ]
