# Generated by Django 2.0.1 on 2018-02-19 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20180212_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('about_me', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
