# Generated by Django 2.0.1 on 2018-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
