# Generated by Django 2.0.1 on 2018-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='github',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(default='', max_length=20),
        ),
    ]
