# Generated by Django 2.0.1 on 2018-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180304_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='github',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(max_length=20),
        ),
    ]
