# Generated by Django 2.0.1 on 2018-03-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_userinfo_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='collect',
            field=models.CharField(default='', max_length=200),
        ),
    ]
