# Generated by Django 2.0.1 on 2018-03-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_userinfo_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='collect',
            field=models.CharField(max_length=200),
        ),
    ]
