# Generated by Django 2.0.1 on 2018-03-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180306_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='collect',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
